name: GitHub Build and Testing
run-name: Build and Testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - name: install update
        run: |
          sudo apt-get update
      - name: remove nginx
        run: |
          sudo apt-get remove nginx
      - name: remove libgd3
        run: |
          sudo apt-get remove libgd3
      - name: install gdlib
        run: |
          sudo apt-get install -yq libgd-tools libgd-dev
      - name: install libz
        run: |
          sudo apt-get install zlib1g-dev
      - name: install ssl
        run: |
          sudo apt-get install libssl-dev
      - uses: actions/checkout@v2
      - name: build v8
        run: |
          ./build-v8.sh
      - name: build tea
        run: |
          ./build-tea.py build
      - name: test
        run: |
          ./test.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."